[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"
optimizer = true
optimizer_runs = 200

[profile.release]
via_ir = true
[rpc_endpoints]
mantlesepolia = "https://rpc.sepolia.mantle.xyz"

